vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set clipboard+=unnamedplus")
vim.cmd("set number")
vim.cmd("set number relativenumber")
vim.cmd("set nu rnu")
vim.cmd("inoremap <CR> <CR>x<BS>")

require("config.lazy")
require('config.lsp')
require('config.telescope')
require('config.lsp-telescope')
require('config.keybinding-misc')
